# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vertrags Manager
version: "0.1.0"
slug: Contract Manager
description: Verwalte deine Verträge in Home Assistant
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
