name: "Vertragsmanager"
description: "Verwalte deine Verträge einfach und übersichtlich."
version: "1.0.0"
slug: "contract_manager"
init: false
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8080/tcp: 8080

