name: "Vertragsmanager"
description: "Verwalte deine Verträge einfach und übersichtlich."
version: "1.0.0"
slug: "contract_manager"
init: false
panel_icon: mdi:file-document
startup: services
ingress: true
ingress_port: 1339
ingress_stream: true
webui: "http://[HOST]:8080"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080